apiVersion: v1
kind: ConfigMap
metadata:
  name: node-zombie-detector-config
  namespace: kube-system
data:
  CLUSTER_NAME: ""
  FEISHU_WEBHOOK_URL: "https://open.feishu.cn/open-apis/bot/v2/hook/xxx"
  CHECK_INTERVAL: "30s" # 检查间隔
  ALERT_THRESHOLD: "1m" # 触发告警的阈值
  ALERT_INTERVAL: "10m" # 重复告警的最小间隔
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-zombie-detector
  namespace: kube-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-zombie-detector
  template:
    metadata:
      labels:
        app: node-zombie-detector
    spec:
      serviceAccountName: node-zombie-detector
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - node-zombie-detector
                topologyKey: kubernetes.io/hostname
      containers:
        - name: detector
          image: ghcr.io/zijiren233/node-zombie-detector:latest
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          envFrom:
            - configMapRef:
                name: node-zombie-detector-config
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-zombie-detector
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-zombie-detector
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["nodes"]
    verbs: ["get", "list"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-zombie-detector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: node-zombie-detector
subjects:
  - kind: ServiceAccount
    name: node-zombie-detector
    namespace: kube-system
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: node-zombie-detector
  namespace: kube-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: node-zombie-detector
